# Generated by Django 4.0.6 on 2022-12-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='stick',
            field=models.BooleanField(default=1, verbose_name='КНОПКА'),
            preserve_default=False,
        ),
    ]
